// Code generated by protoc-gen-go. DO NOT EDIT.
// source: manager.proto

package com_cyto_manager

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CommandDefinition_PermissionLevel int32

const (
	CommandDefinition_USER      CommandDefinition_PermissionLevel = 0
	CommandDefinition_MODERATOR CommandDefinition_PermissionLevel = 1
	CommandDefinition_ADMIN     CommandDefinition_PermissionLevel = 2
	CommandDefinition_OWNER     CommandDefinition_PermissionLevel = 3
)

var CommandDefinition_PermissionLevel_name = map[int32]string{
	0: "USER",
	1: "MODERATOR",
	2: "ADMIN",
	3: "OWNER",
}

var CommandDefinition_PermissionLevel_value = map[string]int32{
	"USER":      0,
	"MODERATOR": 1,
	"ADMIN":     2,
	"OWNER":     3,
}

func (x CommandDefinition_PermissionLevel) String() string {
	return proto.EnumName(CommandDefinition_PermissionLevel_name, int32(x))
}

func (CommandDefinition_PermissionLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{4, 0}
}

type GuildQuery struct {
	GuildID              string   `protobuf:"bytes,1,opt,name=guildID,proto3" json:"guildID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GuildQuery) Reset()         { *m = GuildQuery{} }
func (m *GuildQuery) String() string { return proto.CompactTextString(m) }
func (*GuildQuery) ProtoMessage()    {}
func (*GuildQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{0}
}

func (m *GuildQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GuildQuery.Unmarshal(m, b)
}
func (m *GuildQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GuildQuery.Marshal(b, m, deterministic)
}
func (m *GuildQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GuildQuery.Merge(m, src)
}
func (m *GuildQuery) XXX_Size() int {
	return xxx_messageInfo_GuildQuery.Size(m)
}
func (m *GuildQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_GuildQuery.DiscardUnknown(m)
}

var xxx_messageInfo_GuildQuery proto.InternalMessageInfo

func (m *GuildQuery) GetGuildID() string {
	if m != nil {
		return m.GuildID
	}
	return ""
}

type GuildCommandConfigurationList struct {
	GuildCommandConfigurations []*GuildCommandConfiguration `protobuf:"bytes,1,rep,name=guildCommandConfigurations,proto3" json:"guildCommandConfigurations,omitempty"`
	XXX_NoUnkeyedLiteral       struct{}                     `json:"-"`
	XXX_unrecognized           []byte                       `json:"-"`
	XXX_sizecache              int32                        `json:"-"`
}

func (m *GuildCommandConfigurationList) Reset()         { *m = GuildCommandConfigurationList{} }
func (m *GuildCommandConfigurationList) String() string { return proto.CompactTextString(m) }
func (*GuildCommandConfigurationList) ProtoMessage()    {}
func (*GuildCommandConfigurationList) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{1}
}

func (m *GuildCommandConfigurationList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GuildCommandConfigurationList.Unmarshal(m, b)
}
func (m *GuildCommandConfigurationList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GuildCommandConfigurationList.Marshal(b, m, deterministic)
}
func (m *GuildCommandConfigurationList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GuildCommandConfigurationList.Merge(m, src)
}
func (m *GuildCommandConfigurationList) XXX_Size() int {
	return xxx_messageInfo_GuildCommandConfigurationList.Size(m)
}
func (m *GuildCommandConfigurationList) XXX_DiscardUnknown() {
	xxx_messageInfo_GuildCommandConfigurationList.DiscardUnknown(m)
}

var xxx_messageInfo_GuildCommandConfigurationList proto.InternalMessageInfo

func (m *GuildCommandConfigurationList) GetGuildCommandConfigurations() []*GuildCommandConfiguration {
	if m != nil {
		return m.GuildCommandConfigurations
	}
	return nil
}

type GuildCommandConfiguration struct {
	GuildID              string               `protobuf:"bytes,1,opt,name=guildID,proto3" json:"guildID,omitempty"`
	CommandID            string               `protobuf:"bytes,2,opt,name=commandID,proto3" json:"commandID,omitempty"`
	Enabled              bool                 `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	RoleRestrictions     []string             `protobuf:"bytes,4,rep,name=roleRestrictions,proto3" json:"roleRestrictions,omitempty"`
	ChannelRestrictions  []string             `protobuf:"bytes,5,rep,name=channelRestrictions,proto3" json:"channelRestrictions,omitempty"`
	LastModifiedUserId   string               `protobuf:"bytes,6,opt,name=LastModifiedUserId,json=lastModifiedUserId,proto3" json:"LastModifiedUserId,omitempty"`
	LastModifiedDateUtc  *timestamp.Timestamp `protobuf:"bytes,7,opt,name=LastModifiedDateUtc,json=lastModifiedDateUtc,proto3" json:"LastModifiedDateUtc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GuildCommandConfiguration) Reset()         { *m = GuildCommandConfiguration{} }
func (m *GuildCommandConfiguration) String() string { return proto.CompactTextString(m) }
func (*GuildCommandConfiguration) ProtoMessage()    {}
func (*GuildCommandConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{2}
}

func (m *GuildCommandConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GuildCommandConfiguration.Unmarshal(m, b)
}
func (m *GuildCommandConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GuildCommandConfiguration.Marshal(b, m, deterministic)
}
func (m *GuildCommandConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GuildCommandConfiguration.Merge(m, src)
}
func (m *GuildCommandConfiguration) XXX_Size() int {
	return xxx_messageInfo_GuildCommandConfiguration.Size(m)
}
func (m *GuildCommandConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_GuildCommandConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_GuildCommandConfiguration proto.InternalMessageInfo

func (m *GuildCommandConfiguration) GetGuildID() string {
	if m != nil {
		return m.GuildID
	}
	return ""
}

func (m *GuildCommandConfiguration) GetCommandID() string {
	if m != nil {
		return m.CommandID
	}
	return ""
}

func (m *GuildCommandConfiguration) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *GuildCommandConfiguration) GetRoleRestrictions() []string {
	if m != nil {
		return m.RoleRestrictions
	}
	return nil
}

func (m *GuildCommandConfiguration) GetChannelRestrictions() []string {
	if m != nil {
		return m.ChannelRestrictions
	}
	return nil
}

func (m *GuildCommandConfiguration) GetLastModifiedUserId() string {
	if m != nil {
		return m.LastModifiedUserId
	}
	return ""
}

func (m *GuildCommandConfiguration) GetLastModifiedDateUtc() *timestamp.Timestamp {
	if m != nil {
		return m.LastModifiedDateUtc
	}
	return nil
}

type CommandDefinitionList struct {
	CommandDefinitions   []*CommandDefinition `protobuf:"bytes,1,rep,name=CommandDefinitions,json=commandDefinitions,proto3" json:"CommandDefinitions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CommandDefinitionList) Reset()         { *m = CommandDefinitionList{} }
func (m *CommandDefinitionList) String() string { return proto.CompactTextString(m) }
func (*CommandDefinitionList) ProtoMessage()    {}
func (*CommandDefinitionList) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{3}
}

func (m *CommandDefinitionList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandDefinitionList.Unmarshal(m, b)
}
func (m *CommandDefinitionList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandDefinitionList.Marshal(b, m, deterministic)
}
func (m *CommandDefinitionList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandDefinitionList.Merge(m, src)
}
func (m *CommandDefinitionList) XXX_Size() int {
	return xxx_messageInfo_CommandDefinitionList.Size(m)
}
func (m *CommandDefinitionList) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandDefinitionList.DiscardUnknown(m)
}

var xxx_messageInfo_CommandDefinitionList proto.InternalMessageInfo

func (m *CommandDefinitionList) GetCommandDefinitions() []*CommandDefinition {
	if m != nil {
		return m.CommandDefinitions
	}
	return nil
}

type CommandDefinition struct {
	CommandID            string                            `protobuf:"bytes,1,opt,name=commandID,proto3" json:"commandID,omitempty"`
	Enabled              bool                              `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Triggers             []string                          `protobuf:"bytes,3,rep,name=triggers,proto3" json:"triggers,omitempty"`
	PermissionLevel      CommandDefinition_PermissionLevel `protobuf:"varint,4,opt,name=permissionLevel,proto3,enum=com.cyto.manager.CommandDefinition_PermissionLevel" json:"permissionLevel,omitempty"`
	ParameterDefinitions []*CommandParameterDefinition     `protobuf:"bytes,5,rep,name=parameterDefinitions,proto3" json:"parameterDefinitions,omitempty"`
	LastModifiedUserID   string                            `protobuf:"bytes,6,opt,name=lastModifiedUserID,proto3" json:"lastModifiedUserID,omitempty"`
	LastModifiedDateUtc  *timestamp.Timestamp              `protobuf:"bytes,7,opt,name=lastModifiedDateUtc,proto3" json:"lastModifiedDateUtc,omitempty"`
	Description          string                            `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Unlisted             bool                              `protobuf:"varint,9,opt,name=unlisted,proto3" json:"unlisted,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *CommandDefinition) Reset()         { *m = CommandDefinition{} }
func (m *CommandDefinition) String() string { return proto.CompactTextString(m) }
func (*CommandDefinition) ProtoMessage()    {}
func (*CommandDefinition) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{4}
}

func (m *CommandDefinition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandDefinition.Unmarshal(m, b)
}
func (m *CommandDefinition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandDefinition.Marshal(b, m, deterministic)
}
func (m *CommandDefinition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandDefinition.Merge(m, src)
}
func (m *CommandDefinition) XXX_Size() int {
	return xxx_messageInfo_CommandDefinition.Size(m)
}
func (m *CommandDefinition) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandDefinition.DiscardUnknown(m)
}

var xxx_messageInfo_CommandDefinition proto.InternalMessageInfo

func (m *CommandDefinition) GetCommandID() string {
	if m != nil {
		return m.CommandID
	}
	return ""
}

func (m *CommandDefinition) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *CommandDefinition) GetTriggers() []string {
	if m != nil {
		return m.Triggers
	}
	return nil
}

func (m *CommandDefinition) GetPermissionLevel() CommandDefinition_PermissionLevel {
	if m != nil {
		return m.PermissionLevel
	}
	return CommandDefinition_USER
}

func (m *CommandDefinition) GetParameterDefinitions() []*CommandParameterDefinition {
	if m != nil {
		return m.ParameterDefinitions
	}
	return nil
}

func (m *CommandDefinition) GetLastModifiedUserID() string {
	if m != nil {
		return m.LastModifiedUserID
	}
	return ""
}

func (m *CommandDefinition) GetLastModifiedDateUtc() *timestamp.Timestamp {
	if m != nil {
		return m.LastModifiedDateUtc
	}
	return nil
}

func (m *CommandDefinition) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CommandDefinition) GetUnlisted() bool {
	if m != nil {
		return m.Unlisted
	}
	return false
}

type CommandParameterDefinition struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Pattern              string   `protobuf:"bytes,2,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Optional             bool     `protobuf:"varint,3,opt,name=optional,proto3" json:"optional,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandParameterDefinition) Reset()         { *m = CommandParameterDefinition{} }
func (m *CommandParameterDefinition) String() string { return proto.CompactTextString(m) }
func (*CommandParameterDefinition) ProtoMessage()    {}
func (*CommandParameterDefinition) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{5}
}

func (m *CommandParameterDefinition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandParameterDefinition.Unmarshal(m, b)
}
func (m *CommandParameterDefinition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandParameterDefinition.Marshal(b, m, deterministic)
}
func (m *CommandParameterDefinition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandParameterDefinition.Merge(m, src)
}
func (m *CommandParameterDefinition) XXX_Size() int {
	return xxx_messageInfo_CommandParameterDefinition.Size(m)
}
func (m *CommandParameterDefinition) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandParameterDefinition.DiscardUnknown(m)
}

var xxx_messageInfo_CommandParameterDefinition proto.InternalMessageInfo

func (m *CommandParameterDefinition) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CommandParameterDefinition) GetPattern() string {
	if m != nil {
		return m.Pattern
	}
	return ""
}

func (m *CommandParameterDefinition) GetOptional() bool {
	if m != nil {
		return m.Optional
	}
	return false
}

func init() {
	proto.RegisterEnum("com.cyto.manager.CommandDefinition_PermissionLevel", CommandDefinition_PermissionLevel_name, CommandDefinition_PermissionLevel_value)
	proto.RegisterType((*GuildQuery)(nil), "com.cyto.manager.GuildQuery")
	proto.RegisterType((*GuildCommandConfigurationList)(nil), "com.cyto.manager.GuildCommandConfigurationList")
	proto.RegisterType((*GuildCommandConfiguration)(nil), "com.cyto.manager.GuildCommandConfiguration")
	proto.RegisterType((*CommandDefinitionList)(nil), "com.cyto.manager.CommandDefinitionList")
	proto.RegisterType((*CommandDefinition)(nil), "com.cyto.manager.CommandDefinition")
	proto.RegisterType((*CommandParameterDefinition)(nil), "com.cyto.manager.CommandParameterDefinition")
}

func init() { proto.RegisterFile("manager.proto", fileDescriptor_cde9ec64f0d2c859) }

var fileDescriptor_cde9ec64f0d2c859 = []byte{
	// 637 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xef, 0x4e, 0x13, 0x4f,
	0x14, 0x65, 0xdb, 0x02, 0xed, 0x25, 0xfc, 0xe8, 0xef, 0x22, 0x66, 0x5d, 0x21, 0x6e, 0xd6, 0x44,
	0x1b, 0x35, 0x8b, 0x29, 0x2f, 0x20, 0x61, 0x1b, 0xd2, 0x84, 0x02, 0x0e, 0x10, 0x13, 0x13, 0x13,
	0x87, 0xdd, 0xdb, 0x75, 0xe2, 0xfe, 0xcb, 0xec, 0xd4, 0x04, 0x9f, 0xc1, 0xe7, 0xf0, 0x5d, 0xfc,
	0xec, 0x0b, 0x99, 0x9d, 0xfe, 0x91, 0x76, 0x59, 0x42, 0x13, 0xbf, 0xcd, 0x9d, 0x7b, 0xee, 0xcc,
	0x9d, 0x73, 0xce, 0x5c, 0xd8, 0x8c, 0x79, 0xc2, 0x43, 0x92, 0x6e, 0x26, 0x53, 0x95, 0x62, 0xdb,
	0x4f, 0x63, 0xd7, 0xbf, 0x51, 0xa9, 0x3b, 0xd9, 0xb7, 0x9e, 0x86, 0x69, 0x1a, 0x46, 0xb4, 0xaf,
	0xf3, 0xd7, 0xa3, 0xe1, 0x3e, 0xc5, 0x99, 0xba, 0x19, 0xc3, 0xad, 0x67, 0x8b, 0x49, 0x25, 0x62,
	0xca, 0x15, 0x8f, 0xb3, 0x31, 0xc0, 0x79, 0x01, 0x70, 0x3c, 0x12, 0x51, 0xf0, 0x7e, 0x44, 0xf2,
	0x06, 0x4d, 0x58, 0x0f, 0x8b, 0xa8, 0xef, 0x99, 0x86, 0x6d, 0x74, 0x5a, 0x6c, 0x1a, 0x3a, 0x3f,
	0x0c, 0xd8, 0xd3, 0xc0, 0xa3, 0x34, 0x8e, 0x79, 0x12, 0x1c, 0xa5, 0xc9, 0x50, 0x84, 0x23, 0xc9,
	0x95, 0x48, 0x93, 0x13, 0x91, 0x2b, 0xfc, 0x0a, 0x56, 0x58, 0x05, 0xc8, 0x4d, 0xc3, 0xae, 0x77,
	0x36, 0xba, 0xaf, 0xdd, 0xc5, 0xf6, 0xdd, 0xca, 0x43, 0xd9, 0x3d, 0xc7, 0x39, 0xbf, 0x6a, 0xf0,
	0xa4, 0xb2, 0xb2, 0xfa, 0x19, 0xb8, 0x0b, 0x2d, 0x7f, 0x5c, 0xd1, 0xf7, 0xcc, 0x9a, 0xce, 0xfd,
	0xdd, 0x28, 0xea, 0x28, 0xe1, 0xd7, 0x11, 0x05, 0x66, 0xdd, 0x36, 0x3a, 0x4d, 0x36, 0x0d, 0xf1,
	0x15, 0xb4, 0x65, 0x1a, 0x11, 0xa3, 0x5c, 0x49, 0xe1, 0x8f, 0x9f, 0xd4, 0xb0, 0xeb, 0x9d, 0x16,
	0x2b, 0xed, 0xe3, 0x5b, 0xd8, 0xf6, 0xbf, 0xf0, 0x24, 0xa1, 0x68, 0x0e, 0xbe, 0xaa, 0xe1, 0x77,
	0xa5, 0xd0, 0x05, 0x3c, 0xe1, 0xb9, 0x1a, 0xa4, 0x81, 0x18, 0x0a, 0x0a, 0xae, 0x72, 0x92, 0xfd,
	0xc0, 0x5c, 0xd3, 0xed, 0x61, 0x54, 0xca, 0xe0, 0x09, 0x6c, 0xdf, 0xc6, 0x7b, 0x5c, 0xd1, 0x95,
	0xf2, 0xcd, 0x75, 0xdb, 0xe8, 0x6c, 0x74, 0x2d, 0x77, 0xac, 0xb9, 0x3b, 0xd5, 0xdc, 0xbd, 0x9c,
	0x6a, 0xce, 0xb6, 0xa3, 0x72, 0x99, 0x13, 0xc1, 0xce, 0x84, 0x45, 0x8f, 0x86, 0x22, 0x11, 0x33,
	0x45, 0x2f, 0x00, 0x4b, 0x89, 0xa9, 0x92, 0xcf, 0xcb, 0x4a, 0x96, 0xb0, 0x0c, 0xfd, 0x52, 0xb9,
	0xf3, 0xb3, 0x01, 0xff, 0x97, 0x90, 0xf3, 0xba, 0x18, 0xf7, 0xe8, 0x52, 0x9b, 0xd7, 0xc5, 0x82,
	0xa6, 0x92, 0x22, 0x0c, 0x49, 0xe6, 0x66, 0x5d, 0x13, 0x3c, 0x8b, 0xf1, 0x13, 0x6c, 0x65, 0x24,
	0x63, 0x91, 0xe7, 0xc5, 0x83, 0xe8, 0x1b, 0x45, 0x66, 0xc3, 0x36, 0x3a, 0xff, 0x75, 0x0f, 0x1e,
	0xd0, 0xbb, 0x7b, 0x3e, 0x5f, 0xca, 0x16, 0xcf, 0xc2, 0xcf, 0xf0, 0x28, 0xe3, 0x92, 0xc7, 0xa4,
	0x48, 0xde, 0xe6, 0x67, 0x55, 0xf3, 0xf3, 0xa6, 0xf2, 0x8e, 0xf3, 0x72, 0x11, 0xbb, 0xf3, 0xa4,
	0xc2, 0x16, 0x25, 0xf1, 0xbd, 0x4a, 0x5b, 0x78, 0x85, 0x2d, 0xa2, 0x7f, 0x66, 0x0b, 0xb4, 0x61,
	0x23, 0xa0, 0xdc, 0x97, 0x22, 0x2b, 0xba, 0x31, 0x9b, 0xfa, 0xda, 0xdb, 0x5b, 0x05, 0xf9, 0xa3,
	0x24, 0x12, 0xb9, 0xa2, 0xc0, 0x6c, 0x69, 0x5d, 0x66, 0xb1, 0xf3, 0x0e, 0xb6, 0x16, 0x18, 0xc4,
	0x26, 0x34, 0xae, 0x2e, 0x7a, 0xac, 0xbd, 0x82, 0x9b, 0xd0, 0x1a, 0x9c, 0x79, 0x3d, 0x76, 0x78,
	0x79, 0xc6, 0xda, 0x06, 0xb6, 0x60, 0xf5, 0xd0, 0x1b, 0xf4, 0x4f, 0xdb, 0xb5, 0x62, 0x79, 0xf6,
	0xe1, 0xb4, 0xc7, 0xda, 0x75, 0x67, 0x08, 0x56, 0x35, 0x63, 0x88, 0xd0, 0x48, 0x78, 0x4c, 0x13,
	0xaf, 0xe8, 0x75, 0x61, 0x93, 0x8c, 0x2b, 0x45, 0x32, 0x99, 0x7c, 0xed, 0x69, 0x58, 0x74, 0x9a,
	0xea, 0x9e, 0x79, 0x34, 0xf9, 0xd9, 0xb3, 0xb8, 0xfb, 0xbb, 0x06, 0xeb, 0x83, 0xb1, 0x44, 0xf8,
	0x11, 0x76, 0x8e, 0x49, 0x95, 0x4d, 0x8f, 0x8f, 0x4b, 0xec, 0xf5, 0x8a, 0x29, 0x6b, 0xbd, 0x7c,
	0x80, 0x95, 0x8a, 0xbf, 0xe4, 0xac, 0x60, 0x06, 0x7b, 0xc7, 0xa4, 0x2a, 0x87, 0x56, 0x8e, 0xbb,
	0x15, 0xc3, 0x51, 0x8f, 0x66, 0x6b, 0x7f, 0x89, 0xd1, 0x39, 0xb9, 0xf1, 0x3b, 0xec, 0x5e, 0xdc,
	0x73, 0x23, 0x2e, 0x33, 0x8d, 0xad, 0x65, 0xc0, 0xce, 0xca, 0xf5, 0x9a, 0x26, 0xea, 0xe0, 0x4f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x03, 0x7a, 0xe4, 0x70, 0xbf, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ManagerClient is the client API for Manager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ManagerClient interface {
	GetCommandDefinitions(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*CommandDefinitionList, error)
	GetGuildCommandConfigurations(ctx context.Context, in *GuildQuery, opts ...grpc.CallOption) (*GuildCommandConfigurationList, error)
	SetGuildCommandConfiguration(ctx context.Context, in *GuildCommandConfiguration, opts ...grpc.CallOption) (*GuildCommandConfiguration, error)
}

type managerClient struct {
	cc *grpc.ClientConn
}

func NewManagerClient(cc *grpc.ClientConn) ManagerClient {
	return &managerClient{cc}
}

func (c *managerClient) GetCommandDefinitions(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*CommandDefinitionList, error) {
	out := new(CommandDefinitionList)
	err := c.cc.Invoke(ctx, "/com.cyto.manager.Manager/GetCommandDefinitions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) GetGuildCommandConfigurations(ctx context.Context, in *GuildQuery, opts ...grpc.CallOption) (*GuildCommandConfigurationList, error) {
	out := new(GuildCommandConfigurationList)
	err := c.cc.Invoke(ctx, "/com.cyto.manager.Manager/GetGuildCommandConfigurations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) SetGuildCommandConfiguration(ctx context.Context, in *GuildCommandConfiguration, opts ...grpc.CallOption) (*GuildCommandConfiguration, error) {
	out := new(GuildCommandConfiguration)
	err := c.cc.Invoke(ctx, "/com.cyto.manager.Manager/SetGuildCommandConfiguration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManagerServer is the server API for Manager service.
type ManagerServer interface {
	GetCommandDefinitions(context.Context, *empty.Empty) (*CommandDefinitionList, error)
	GetGuildCommandConfigurations(context.Context, *GuildQuery) (*GuildCommandConfigurationList, error)
	SetGuildCommandConfiguration(context.Context, *GuildCommandConfiguration) (*GuildCommandConfiguration, error)
}

// UnimplementedManagerServer can be embedded to have forward compatible implementations.
type UnimplementedManagerServer struct {
}

func (*UnimplementedManagerServer) GetCommandDefinitions(ctx context.Context, req *empty.Empty) (*CommandDefinitionList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommandDefinitions not implemented")
}
func (*UnimplementedManagerServer) GetGuildCommandConfigurations(ctx context.Context, req *GuildQuery) (*GuildCommandConfigurationList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGuildCommandConfigurations not implemented")
}
func (*UnimplementedManagerServer) SetGuildCommandConfiguration(ctx context.Context, req *GuildCommandConfiguration) (*GuildCommandConfiguration, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetGuildCommandConfiguration not implemented")
}

func RegisterManagerServer(s *grpc.Server, srv ManagerServer) {
	s.RegisterService(&_Manager_serviceDesc, srv)
}

func _Manager_GetCommandDefinitions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).GetCommandDefinitions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.cyto.manager.Manager/GetCommandDefinitions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).GetCommandDefinitions(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_GetGuildCommandConfigurations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GuildQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).GetGuildCommandConfigurations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.cyto.manager.Manager/GetGuildCommandConfigurations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).GetGuildCommandConfigurations(ctx, req.(*GuildQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_SetGuildCommandConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GuildCommandConfiguration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).SetGuildCommandConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.cyto.manager.Manager/SetGuildCommandConfiguration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).SetGuildCommandConfiguration(ctx, req.(*GuildCommandConfiguration))
	}
	return interceptor(ctx, in, info, handler)
}

var _Manager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.cyto.manager.Manager",
	HandlerType: (*ManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCommandDefinitions",
			Handler:    _Manager_GetCommandDefinitions_Handler,
		},
		{
			MethodName: "GetGuildCommandConfigurations",
			Handler:    _Manager_GetGuildCommandConfigurations_Handler,
		},
		{
			MethodName: "SetGuildCommandConfiguration",
			Handler:    _Manager_SetGuildCommandConfiguration_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "manager.proto",
}
